services:
  - type: web
    name: ai-dream-weaver-bot
    runtime: image
    repo: https://github.com/casperblac991/ai-dream-weaver
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthcheck
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: UNSPLASH_ACCESS_KEY
        sync: false
      - key: STORE_URL
        value: https://aidreamweaver.store
